name: Project Board

on:
  issues:
    types: [opened]

jobs:
  project:
    runs-on: ubuntu-latest

    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          token: ${{ secrets.PAT }}
          project-location: iearn-finance
          project-name: Web
          column-name: Back log
