name: Telegram
on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          😍 A YIP pull request has been merged on GitHub!
          Commit Message: ${{ github.event.head_commit.message }}
          Commited Actor: ${{ github.actor }}
